### ISSUE TITLE
ImproperlyConfigured error

### ISSUE THREAD

**Issue by lkeijser** [liberation/django-mptt-comments#2]
Hi, 

I'm getting this error using the latest checkout:

'MpttCommentsAdmin.raw_id_fields' refers to field 'parent' that is missing from model 'Comment'.

my settings.py (excerpt) :

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    'captcha',
    'gravatar',
    'django_autoslug',
    #'profiles',
    'registration',
    'notification',
    'django.contrib.humanize',
    'django.contrib.comments',
    'django.contrib.markup',
    'template_utils',
    'mptt',
    'mptt_comments',
    'taggit',
    'taggit_templatetags',
    'blog.web',
    'south',
)

hope you can help me :)

thanks,

Léon

**Comment by diox** [comment]
Did you define COMMENTS_APP in your settings.py ? It needs to point to mptt_comments (unless you are using your own variant extending one of the provided models)

**Comment by lkeijser** [comment]
Uh, no I didn't. That fixed it, thanks :)
