### ISSUE TITLE
unexpected error when previewing

### ISSUE THREAD

**Issue by lkeijser** [liberation/django-mptt-comments#4]
When hitting the Preview button (after I'm logged in) I get the following error:

 An unexpected error occured. Please try again in a few minutes

My urls.py : http://dpaste.com/695050/
My settings.py : http://dpaste.com/695052/

Thanks in advance,

Léon

**Comment by diox** [comment]
Use the non-ajax version (just disable JavaScript) or use Firebug/Web Inspector to look at the content of the XHR response. It's probably a 500 or a 400, but the JavaScript hides the real error for the user.

**Comment by lkeijser** [comment]
Stupid. Forgot to include the mptt_comments_media in the HEAD section (included it in BODY by accident). However, now I'm getting:

```
CSRF token missing or incorrect.
```

when hitting Preview.

(i'm looking like such a noob ... sorry about that)

**Comment by lkeijser** [comment]
Okay, I guess it's because the csrftoken isn't sent in the javascript POST function. I'm going to try to modify the .js file and see if I can get it working. If you have already solved this problem, please let me know :) Else I'll do a pull request if i get it working (new file probably, to support both methods?).

**Comment by diox** [comment]
IIRC ajax posts don't require the token. Furthermore, since the post is made by using $(":input", form).serializeArray(), the XHR request should contain the CSRF token. I can't reproduce this problem.

**Comment by lkeijser** [comment]
According to this page: https://docs.djangoproject.com/en/1.3/ref/contrib/csrf/#ajax they do require it. After adding the js code, I don't get the csrf error anymore. Seems like the only thing going wrong now is this error:

```
Caught NoReverseMatch while rendering: Reverse for 'comment-detail' with arguments '(None,)' and keyword arguments '{}' not found.
```

**Comment by lkeijser** [comment]
Update on this issue. I noticed I didn't have anything enabled for django-notification in my urlconf. So now it looks like this:

```
# comments
(r'^jsi18n/(?P<packages>\S+?)/$', javascript_catalog),
(r'^comments/', include('mptt_comments.urls')),
(r'^comments/', include('notification.urls')),
(r'^comments/', include('django.contrib.comments.urls')),
```

And after commenting out the 'Preview' button in form.html , it now works :)  Two things that kind of bother me still though:
1. why doesn't it work when i hit Preview (i get the abovementioned NoReversematch error
2. when I submit a comment, the form gets replaced by a text "Your comment was posted" and only after reloading the page, the form reappears. How can I always show the form?

thanks for your patience and nice work :)

**Comment by lkeijser** [comment]
I looked at Firebug while posting and something weird happens. The form gets POSTed succesfully, but then it tries to post it again :

```
POST http://localhost:8000/comments/post/ 302 FOUND     549ms   
POST http://localhost:8000/comments/post/ 400 BAD REQUEST   544ms   
"NetworkError: 400 BAD REQUEST - http://localhost:8000/comments/post/"    /comments/post/
GET http://localhost:8000/comments/posted-ajax/?c=27  201 CREATED   35ms    
```

Any idea?

**Comment by lkeijser** [comment]
I'm an idiot :(   Included the .js file twice .. Feel free to laugh and mock me and stuff

**Comment by diox** [comment]
:) Not a problem. Still doesn't explain the NoReverseMatch problem. Can you open a specific issue about that, re-explaining the issue without all the other comments ? It might be a problem in the default templates, I don't use them all in the main project that uses mptt_comments, so I might have forgot to update one of them.
